---

- name: Bootstrap cluster 
  hosts: maria[0]
  become: true
  roles:
    - gelara
  vars:
    bootstrap_cluster: 'yes'
  tags:
    - bootstrap

- name: Add masters to cluster
  hosts:
    - "!maria[0]"
    - maria
  become: true
  roles:
    - gelara
  tags:
    - masters
