{
 "title": "Custom exporter",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Cpu usage",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "psutil_cpu_percent", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Memory usage",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "psutil_virtual_memory_percent", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Gelara cluster size",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "wsrep_cluster_size", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}