- name: Set default gateway fact
  ansible.builtin.set_fact:
    default_gateway: "{{ hostvars[groups['gateway'].0].ansible_host }}"
  when: default_gateway is undefined

- name: Remove default gateway
  become: true
  ansible.builtin.command: "ip route del default"
  ignore_errors: true
  changed_when: false

- name: Set default gateway
  become: true
  ansible.builtin.command: "ip route add default via {{ default_gateway }}"
  changed_when: false
