---
- name: Enable packet forwarding
  ansible.builtin.lineinfile:
    dest: "/etc/sysctl.conf"
    regexp: '^(#\s*)?net.ipv4.ip_forward'
    line: "net.ipv4.ip_forward = 1"
  notify: Apply sysctl

- name: Configure forwarding with Iptables
  ansible.builtin.import_tasks: iptables.yml
