---
- name: Install docker from ubuntu repository
  ansible.builtin.apt:
    name: docker.io
    state: present
    update_cache: true

- name: Template daemon.json for docker iran
  ansible.builtin.template:
    src: "daemon.json.j2"
    dest: "/etc/docker/daemon.json"
    owner: root
    group: root
    mode: "0644"
  notify: Restart docker service
